### ISSUE TITLE
Display date correctly

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/messaging-fe#111]
In the table of folder messages and message headers, display the date correctly. This includes making it display relative to the current time ('Today', 'Yesterday', etc.) and timezone.

**Comment by U-DON** [comment]
@angel What’s the format for how we display dates? Like if the date is today, do we always just display time? Do we ever show something like "Yesterday @ [time]”? And when do we full date with the year? Just throwing out some examples but I wanted to see what all of the rules should be.

**Comment by ahelkit** [comment]
@U-DON 

**For the folders, the dates should be displayed as follows in the table:**
1. If the date is today, display only the time. I'm not sure timezone is neccessary as the time displayed should be in the timezone of the Veteran. "10:57 am"
2. If it was yesterday or anytime in the past within the year, then it would just be the date. "Oct 18"
3. If it was the previous year, then it would be "10/18/2015"

For message, the dates should be displayed as follows:
1. For the message header, "Tue, Oct 18, 2016 at 12:20 PM"
2. For the top of the message on the right,
   a. If it's today, then it should just say the time "12:20 PM"
   b. If it's in the past within the year, then it would be" Oct 18"
   c. If it was the year before, then it would be "10/18/2015"

An enhancement if it's not too hard would be for the past two weeks, if we can do it how Gmail does it with how many mins, hours, days ago up to 14 days, I think that's helpful in scanning the message without having to calculate how long ago this message was. So it would be "Oct 18 (1 day ago)" up to (13 days ago) and then it would just be the date after that "Oct 5". If that makes sense. It would also be cool if we could do minutes and hours too "12:20 PM (1 hour ago)", but I think day would be more useful since it could take up to 72 hours to answer anyways. If this is all too much then the dates or times alone are fine! 

Thanks!

**Comment by U-DON** [comment]
@angel 

By "the message header", do you mean the details that appear when you click on the arrow next to the recipient (on desktop) or 'Details' (on mobile)?

And would the "___ ago" enhancement be on both the table and the message dates?

**Comment by ahelkit** [comment]
@U-DON 

The "message header" are the details that appear when you click on the arrow next to the recipient on desktop as well as the details in mobile. 

The ago enhancement would just be within the message. Something like this: 

Desktop:
![image](https://cloud.githubusercontent.com/assets/103496/19540197/9d552656-9612-11e6-86cc-9bb8d5977168.png)

Mobile:
![image](https://cloud.githubusercontent.com/assets/103496/19540161/6723fc56-9612-11e6-89ef-8bf1a5ac84fe.png)

Also for the time itself, I don't know if Veterans would prefer 24 hour time or a 12 hour time. Maybe that's something we can ask in user testing.

**Comment by U-DON** [comment]
@angel The original mocks showed 24 hour time, so that's what I went with. I can change it to 12 hour.

If we're going with 12 hour, do we standardize on whether to show AM/PM or am/pm? Is it lowercase for the table and uppercase for the message?

Should we show leading zeros for months, days, and hours? Like "01:00 PM" or "01/01/2016"?

Going by Gmail's format, it appears to be lowercase am/pm in the table and uppercase in the message, and there are no leading zeros.

**Comment by U-DON** [comment]
Also, given that there's no date on drafts (it appears we don't have a saved date or anything like that), should we be showing the date column in the Drafts folder? Or just keep the column to be consistent, but show something like 'Not available'?

**Comment by ahelkit** [comment]
@U-DON since you already have 24 hour time, maybe let's go with that and see what Veterans say in testing next week. Don't want you to have to do extra work if we decide not to change it. For 24 hour time I would lead with a zero. For the date, let's lead with a zero since that's the format we use for dates in advanced search. 

For drafts, that's a good question. Are we auto saving the drafts right now? I was thinking it would show the timestamp here. 
![image](https://cloud.githubusercontent.com/assets/103496/19569980/cb8b3390-96ac-11e6-897a-27b419d8e14c.png)

I think either way there should still be a date column for the drafts to let you know when you last touched it. 

Let me know. Thanks!

**Comment by U-DON** [comment]
@angel We haven't added auto-saving yet. The issue is that drafts don't seem to have any date fields available to us, including a save time, so there's no date we can use to fill in that column.

**Comment by ahelkit** [comment]
@U-DON gotcha, sorry I missed read that. You're saying the API doesn't give us a date/time at all?

**Comment by U-DON** [comment]
@angel Right, the only date we have for messages is a sent date, but that field is blank for drafts since they haven't been sent.

**Comment by ahelkit** [comment]
@U-DON sad, really wished we could have that date! Ok, if we don't have a date I think it's better to not have the column then see "not available". I think that would be more confusing.
