### ISSUE TITLE
Clear or cancel search

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/messaging-fe#147]
Currently, aside from clicking the folder in the sidebar, there's no way to clear the current search so that the user can view all the messages in the folder again.

If the user tries to search without anything entered in the fields, that's considered an error, and not a means of clearing the search.

Hence, we need some way to be able to clear all the fields and show the folder without any search filters active.

**Comment by ahelkit** [comment]
@U-DON 

What if when you hover over a search box with a term in it, an "x" appears and when the Veteran clicks the x it clears the search and shows all the messages in that folder? 

![image](https://cloud.githubusercontent.com/assets/103496/19985998/4d5e1150-a1d2-11e6-9084-097b8c1018d5.png)

For advanced search, let's and a "Clear advanced search" link and a cancel button like so. 

![image](https://cloud.githubusercontent.com/assets/103496/19986189/ecea553a-a1d2-11e6-9b5b-fa7b6db79585.png)

"Clear advanced search" would clear all the fields and cancel would close the advanced search and take the Veteran back to the folder with all the messages displaying.

**Comment by webinista** [comment]
> What if when you hover over a search box with a term in it, an "x" appears and when the Veteran clicks the x it clears the search and shows all the messages in that folder?

IIRC, this is how Internet Explorer and Edge handle text and search inputs natively, which means it could be hard to style for those browsers. Not saying "No," but definitely saying "Let's think this through a little more."

This would also be a departure from how our site search box works. Should we try to make them behave the same way? 

One last question, since I'm asking them all :-) : Should we make it clear that this is a search of the current folder, and not an all folders search?

**Comment by ahelkit** [comment]
@webinista being consistent sounds good. How is it handled on our site for clearing? 

Right now, we have the search under each folder name to signal that it is within that folder, but it's pretty subtle. I'm don't think this was something we asked about in user testing (/cc @gnakm). I think it's something we can think more about post launch to make it clearer.

**Comment by webinista** [comment]
The main search box does not have a way to be cleared. Since it also doesn't use the `search=input` type, it also doesn't have the native browser clearing mechanism/icon.

This is what our search box looks like in IE11 and Edge. That ✖️ is part of the IE UI.

<img width="543" alt="screen shot 2016-11-07 at 9 08 02 am" src="https://cloud.githubusercontent.com/assets/354277/20067389/cb105e60-a4c9-11e6-9e68-3a9edb6f023f.png">

But it doesn't exist in most other browsers.

<img width="524" alt="screen shot 2016-11-07 at 9 08 16 am" src="https://cloud.githubusercontent.com/assets/354277/20067442/fb7f2f18-a4c9-11e6-9f45-57097ee2eee9.png">

**Comment by ahelkit** [comment]
@webinista so then instead of having an x we should just clear the search by deleting the text in the box pressing search and then it would show all the messages instead of an error for searching nothing?

**Comment by webinista** [comment]
Yes? I think that's a good plan.
