### ISSUE TITLE
Message Having Attachment -- Save As Draft should alert user

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/messaging-fe#155]
Since saving a message as a draft will not save the attachment, either the control for save as a draft should be disabled or we should put a popup / modal that informs the user that the draft is being saved without the attachment.

<img width="793" alt="draft with attachment" src="https://cloud.githubusercontent.com/assets/591737/20077326/f7072e28-a509-11e6-8bcb-47d71c13e484.png">

**Comment by ayaleloehr** [comment]
Assigning to @angel as this is a UX question

**Comment by ahelkit** [comment]
@saneshark @ayaleloehr Veterans should be able to still attach in case they might send instead of save it as a draft, so instead the second option of a modal that warns them that their draft will be saved without the attachment would be a better experience. Here's what it could look like. I'm not the best wordsmith:

![image](https://cloud.githubusercontent.com/assets/103496/20079100/0d51996e-a4f8-11e6-81ef-8c663e1dc2a6.png)

**Comment by saneshark** [comment]
I think if we say "messages cannot be saved as drafts with attachments." Is that clear enough that, we're saving it, but they would need to reattach attachments when sending the message? I'm not a wordsmith either clearly :)

**Comment by ahelkit** [comment]
@saneshark Would this be more clear? "Drafts cannot be saved with attachments. You'll have to reattach attachments when you're ready to send your message. Would you like to save your message anyway?"

**Comment by ayaleloehr** [comment]
Awesome. that sounds good. and that modal should only appear when 1) clicking save as draft and 2) the user has attached attachment(s) to the message.  Will leave in the backlog for now as Tiffany and Eugene work Rx issues first. To be re-evaluated later this week.
