### ISSUE TITLE
There is too much whitespace next to the pagination controls

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/messaging-fe#156]
Maybe the pagination controls should be shrunk down, padding removed, maybe they should be moved to the bottom. But there is too much whitespace below the search bar and where the actual listing of messages begins. I'm not sure what the best solution is, but the most important thing for me to see when I click on a folder is the messages... instead search and pagination controls stand out far too prominently.

<img width="1069" alt="too much whitespace next to pagination controls" src="https://cloud.githubusercontent.com/assets/591737/20077382/220e084e-a50a-11e6-8acb-d30e0d7f568e.png">

**Comment by ahelkit** [comment]
@saneshark Thanks for the feedback! I agree that there is a lot of white space on the left hand side. Right now, we could at least reduce the padding between the previous and next and the gray bar by half to bring the list up a little. 

Originally in this design there were more controls over to the left where there is currently white space that would allow for bulk moving or deleting, but since the API does not support those actions at this time, we took those out. I left that area there so we had room for those controls in the future.

Additionally the since the API does not allow for searching all messages I moved the search under the folder name for now to signify that you are searching within that folder. 

I think that it's nice to see the number of messages directly above the list. This is more relevant once a Veteran has a larger number of messages, unlike the example above. I would prefer to keep the design as is for now since to my knowledge we didn't have any Veterans comment on this during user testing (/cc @gnakm). In any case, I am happy to revisit this post launch.

**Comment by bshyong** [comment]
Is this still an issue or can we close this card?

**Comment by ayaleloehr** [comment]
i would categorize this as a visual preference. Will let @angel make the call if there is anything we should change now or just close this. I'm fine to close.

**Comment by ahelkit** [comment]
@ayaleloehr @bshyong I'm fine to close it for now as well and we can revisit this later. Thanks for checking!
