### ISSUE TITLE
DeleteMessage component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#16]
**UPDATE:** For now, only one message at a time can be moved. Still need the _Move to Deleted_ button. (See discussion below.)

Allows veteran to select all messages and move them to the deleted folder.

<img width="219" alt="screen shot 2016-09-01 at 1 28 36 pm" src="https://cloud.githubusercontent.com/assets/354277/18183196/1b33aa66-7048-11e6-9b26-f5743ea2cee7.png">

**[Inbox mode](https://marvelapp.com/159dfd8#14607420)**: Button should say "Move to deleted"
**[Drafts mode](https://marvelapp.com/159dfd8#14605148)**: Button should read "Delete draft"
**[Deleted mode](https://marvelapp.com/159dfd8#14607246)** Button should read "Move to inbox"

Blocks #3

**Comment by webinista** [comment]
@angel 
- Are there delete options hidden behind the arrow?
- On the [Sent](https://marvelapp.com/159dfd8#14605153) screen, there's a check box but no delete button. What should the check box do there?

(When you post answers here, feel free to un-assign yourself)

**Comment by ahelkit** [comment]
@webinista 
1. If a user clicked on the arrow. It would show options for the user to select messages by all, none, unread, read. I think we are punting on this for now as we can't do any sort of bulk moving. Also, since right now we haven't added folders the only action the user has to take is move the message to deleted. What I had in mind here was that the "Move to deleted" button would be grayed out and then when the user selects a message it would be darker and clickable. 
2. The sent screen mistakenly has a checkbox dropdown. A user will not be able to move any of the messages out of the sent screen. I will remove it from the mock shortly. 

Let me know if there's anything I described above that doesn't make sense. Thanks!

**Comment by webinista** [comment]
Okay, so for now, we aren't building this? I'll close with an _invalid_ label. We can always re-open it if things change.

**Comment by ahelkit** [comment]
@webinista I think we still build the move to delete button, just not the checkbox dropdown. So users can still check a message in the list of messages and delete that one individually. @ayaleloehr can you confirm that I got that correctly? Thanks!

**Comment by webinista** [comment]
My understanding is that we need to implement a task queue or bulk delete on the server side first. Making Select All/Unread/Read/None work on the front end is (relatively) easy. But handling that on the server is not.

**Comment by ayaleloehr** [comment]
That is a correct understanding @webinista (unfortunately, as bulk actions are expected by users I really wish it was in the API, but it just isn't right now).  There should definitely still be a "move to deleted" button, but we will just only be able to do it on one message at a time.

**Comment by webinista** [comment]
Closing. This feature is being replaced by the MoveTo component (#44)
