### ISSUE TITLE
MessageAttachments

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#27]
View for attachments list.

<img width="693" alt="screen shot 2016-09-01 at 2 08 21 pm" src="https://cloud.githubusercontent.com/assets/354277/18184355/926e4cda-704d-11e6-97b5-9312bd6dd396.png">
#### Blocks
- #26 Message component
- #31 MessageSend component
- #35 MessageCompose component

**Comment by webinista** [comment]
### Questions
- What will multiple attachments look like? Are they even supported?

**Comment by webinista** [comment]
Current application support level:
- Up to 4 files may be uploaded at once.
- Files must be one of the following formats:
  - txt
  - pdf
  - doc
  - docx
  - xls
  - gif
  - jpg
  - rtf
  - xlsx
  - png

**Comment by webinista** [comment]
Assigning it to you, Angel/Gina/Emily. I think we still need an attachments flow. Current product supports multiple file uploads.

We can use the [`multiple` attribute](http://caniuse.com/#feat=input-file-multiple) in HTML5 to allow multiple file uploads in browsers that support it. It works just like a single file upload. But for users with older browsers (e.g ≤ IE9), that won't work.

**Comment by ahelkit** [comment]
@webinista 

Here's what we have for the attachment flow. 

**Desktop:**

For desktop, you can click through marvel here: https://marvelapp.com/1bdd199/screen/15110363. Click attach a file and go through the flow from there. 

The steps are:
1. Click "attach a file".
2. Select a file from the native file upload dialog. We opted to have the attach a file go directly to the file upload instead of a modal because it reduce the number of clicks and is what Veterans would be use to based on other email clients. 
3. Your file is attached to the message. You can click the "x" to delete the message. 

If the Veteran wants to add another message they can click "attach a file" again and go through the same steps and that file would be added below the previous file. 

If the file the Veteran choose exceeds the size limit. Then a modal will pop up like this: 
![attachment-size-limit](https://cloud.githubusercontent.com/assets/103496/18530972/c42664b6-7a88-11e6-9b3d-45b4217804e1.jpg)

**Mobile:**

For mobile, you can click through marvel here: https://marvelapp.com/12c67dg/screen/15166114.
Click attach a file and go through the flow from there. 

Here the steps are:
1. Tap "attach a file"
2. The native "take a photo or choose from library" pops on the bottom. 
3. The Veteran selects a picture and then it gets added. I've seen on iPhones that once you select an image you can choose size of the image you want to attach, but don't know how that is in Android. 

Also, we put it so you can see a little example of the picture, so Veterans can see what they are including since images from your phone don't have useful names. 

If the file the Veteran choose exceeds the size limit. Then a modal will pop up like this: 
![image](https://cloud.githubusercontent.com/assets/103496/18531204/ee05c28a-7a89-11e6-9bab-7c9555285c57.png)

Also, I don't know the actual size limits. That was just the information in the MHV prototype: 
![image](https://cloud.githubusercontent.com/assets/103496/18531384/f2e3f618-7a8a-11e6-8fad-8b74f8a2fa22.png)

Ok, let me know if that's enough info to work off of or if anything needs clarification or not possible and needs to be reworked. Thanks!

**Comment by webinista** [comment]
I think this fleshed out view is possible. But I think we'll need a progressively enhanced approach so that IE9 users aren't left in the cold.

**Comment by webinista** [comment]
Right now, the attachments UI looks like this:

![attachments-ui](https://cloud.githubusercontent.com/assets/354277/18969936/2455d8f0-8644-11e6-9bc1-9908a33a8afc.gif)

This action doesn't actually upload the files. It just queues the file names up for sending. 

When do we want to handle the upload? 
1. Asynchronously when the files are added (and maybe with a progress bar)? or
2. Synchronously when the user sends a message or saves a draft

The second option is easier to build on the front end, but will slow down the sending / saving of messages.

In either case, we should probably have a design for the "files are being uploaded" state.

Maybe the answer is to make them get uploaded on send / save draft just to launch things and then add an asynchronous upload.

**Comment by ahelkit** [comment]
@webinista This is awesome!!

I would prefer 1, where there would be a progress bar with each file attached like Gmail. However, if 2 is easier, let's go with 2 for the launch and we can revisit the 1st option later as an enhancement. 

So for 2, it will be:
1. Veteran selects attachments
2. Veteran presses send or save draft
3. Loading bar/gif comes up as attachments are being uploaded and then message gets sent
4. Success message pops up back at inbox 

We will work on what the loading bar/gif will look like and get back to you. Thanks!
