### ISSUE TITLE
AdvancedSearch component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#4]
Should toggle (maybe slide?) open and closed.

[Desktop prototype](https://marvelapp.com/159dfd8/screen/14859117)

<img width="741" alt="screen shot 2016-09-01 at 1 12 57 pm" src="https://cloud.githubusercontent.com/assets/354277/18182689/d9e34e1a-7045-11e6-84b0-8b94613e3e7d.png">

Blocks #14 (SearchBox component)

**Comment by webinista** [comment]
Questions for product / design @staceylanger @angel 
- Are we keeping the _Exact Match_ box? 
- Are any of the Advanced Search fields required?
  - What happens if a veteran tries to submit the form with _None_ of the fields filled out?
- Should the date fields use a [date picker](https://hacker0x01.github.io/react-datepicker/)?

**Comment by ahelkit** [comment]
@webinista 
1. Exact match is a checkbox is something that exists on the current MHV, so I think we should keep it because I think it is still useful for Veterans. If a Veteran did not check the box then whatever they type in the from or the subject would be an or search (Lab tests -> Lab or tests) and if they checked exact match then it would be an and search. (Lab tests -> Lab tests).
2. None of the fields should be required because a Veteran would want to get to choose which field(s) they want to search by.
   a. If none of the fields are filled out, they would get an error message. 
3. The date fields should be date pickers, but also allow the Veteran to type in the date based on the MM/DD/YYYY format. 

I will mock up what the results page would look like for search and what the error would look like when a Veteran doesn't fill out any of the fields.

**Comment by gnakm** [comment]
## Error for empty advanced search

This is look the same for regular empty search except the advanced search won't be expanded but closed instead. 

<img width="259" alt="screen shot 2016-09-08 at 7 56 07 pm" src="https://cloud.githubusercontent.com/assets/13420618/18370882/713a5dcc-75fe-11e6-8a9b-278e5348234d.png">

**Comment by gnakm** [comment]
Desktop view
![search error](https://cloud.githubusercontent.com/assets/13420618/18384555/23eb2de8-7659-11e6-9d9d-da3087a0b408.png)

**Comment by webinista** [comment]
Will make this box "pop" open and closed for now. Will add a transition that makes it slide open / closed later. React's transitions are a bit more complicated to do they are with just CSS.

**Comment by gnakm** [comment]
@webinista Thanks Tiffany
