### ISSUE TITLE
FolderNav component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#5]
Navigation for secure messaging folders. 
- Should highlight link that corresponds to active folder view. 
- Links should trigger a state change that loads the requested view.
- Should contain links to:
  - Inbox view (with a message count)
  - Drafts view (with a message count)
  - Sent view
  - Deleted view
  ##### Mobile only
  - Settings menu (Need to know whether we can provide email notifications first)
  - Help page
### Mobile view:
- Opened by a Menu button
- Closed by a close button.
- Should sit off-screen until requested by the user.
### Desktop view:

_Should not_ contain links to Settings menu and Help page.
#### Desktop view

![screen shot 2016-09-09 at 1 22 30 pm](https://cloud.githubusercontent.com/assets/354277/18401685/89fada16-7690-11e6-8dc0-fec399c18dfd.png)
#### Mobile view

_Note that the mobile view should have the same folders and links_.

<img width="338" alt="screen shot 2016-09-01 at 12 44 46 pm" src="https://cloud.githubusercontent.com/assets/354277/18181811/f7e29154-7041-11e6-96da-f29f39387a1a.png">
- [Desktop prototype](https://marvelapp.com/159dfd8)
- [Mobile prototype](https://marvelapp.com/11jc4c2#14680027?overlay=14680024)
#### Blocks
- #11 SecureMessaging home page
#### Related
- #3 Message list component

**Comment by webinista** [comment]
This uses the [Side navigation](https://standards.usa.gov/sidenav/) component pattern:

**Comment by webinista** [comment]
Folder navigation in mobile view should not be accessible when composing a new message or viewing a message thread. It should be on desktop.

**Comment by webinista** [comment]
@angel @gnakm @emilyville 
- What should happen to the folder list when there are a lot of folders? (For example, the screen shot below) 
  - Specifically should the Manage Folders and Create New Folder buttons just sit at the end of the list? 
  - Should the main folder list be limited in height and scrollable with the Manage Folders and Create New Folder buttons below it?

![screen shot 2016-09-09 at 1 24 32 pm](https://cloud.githubusercontent.com/assets/354277/18401736/d589ce60-7690-11e6-8d43-ecc95d3e0c49.png)
- What should happen if the folder names are really long? (We've handled this on prescriptions by using `text-overflow: ellipsis`.
- On mobile, should the Manage Folders and Create New Folder buttons sit above the settings and help buttons?

**Comment by ahelkit** [comment]
@webinista 

**\-  What should happen to the folder list when there are a lot of folders? (For example, the screen shot below)**
   I think for 1-5 folders, we can just display those like you have it. For 5+ folders, can we collapse it like so:

![image](https://cloud.githubusercontent.com/assets/103496/18444802/9ad4ed9a-78cf-11e6-9a5c-1a9532f26cc4.png)

![image](https://cloud.githubusercontent.com/assets/103496/18444820/a8910ebe-78cf-11e6-8cb1-0253bad69b06.png)

**\- Specifically should the Manage Folders and Create New Folder buttons just sit at the end of the list?**
   The manage folders and create new folder links should still sit at the end of the list. unless in mobile it should be right above the settings and help links. 

**\- Should the main folder list be limited in height and scrollable with the Manage Folders and Create New Folder buttons below it?**
    I think the height should be limited to the heigh of the page for desktop and mobile. so what whatever fits on the page would show and if there are more items pass the height to the page, then it would be scrollable. 

**\- What should happen if the folder names are really long? (We've handled this on prescriptions by using text-overflow: ellipsis.**
  Ellipsis. 

For when a Veteran creates a new folder, can we have validation for duplication, so that they don't have two folders that are named the same thing? 

Also, I noticed that there is a count for deleted in your screenshot. I don't think there needs to be a count for that one. Just for Inbox for when there are unread messages and drafts when there are drafts. Let me know of anything doesn't make sense. Thanks!

**Comment by U-DON** [comment]
@angel To clarify, what should the counts next to each folder indicate? Right now, they're all counts of unread messages. From your last point, am I correct in interpreting that (1) Inbox's count should be number of unread messages and (2) Draft's count should be total number of drafts (both "read" and "unread")? Should Sent have any counts? And none of "My folders" should have counts?

**Comment by ahelkit** [comment]
@U-DON sorry for the confusion. The inbox count should be unread messages and the draft should be the total number of drafts. None of other folders should have counts.
