### ISSUE TITLE
Add character limit to Subject Line field

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#82]
Should have a 512 character max.

**Comment by ayaleloehr** [comment]
Are we concatenating subject line with Category? (that's a question I don't know the answer to...)

If yes, maybe we should have the subject line max length be less than 512 so that when adding Category it doesn't go over?  We could do something smart like (512 - [category text length]), but honestly i would probably just make the max subject line length something smaller like 450 to make your lives easier?

**Comment by webinista** [comment]
After reading a bit more carefully, I think we can assume that we won't concatenate them. Since MHV said that the subject line can be blank, I guess we can just send it to them.
